name: face-recognition
channels:
  - defaults
dependencies:
  - hdf5
  - ipython
  - libopencv=3.4.2
  - numpy
  - opencv=3.4.2
  - pillow=5.3.0
  - py-opencv=3.4.2
  - python=3.6.7
  - spyder
  - wheel

